### ISSUE TITLE
Docker Installation Fail

### ISSUE THREAD

**Issue by jhkwag970** [MapItAnywhere/MapItAnywhere#1]
Hello,

Thank you for your awesome work! As I am trying work with docker file you uploaded, there is error occur due to problem in OpenSfM which make your system fail

This is type of error I got: https://github.com/mapillary/OpenSfM/issues/1080  

Do you happen to know any alternative way to work OpenSfM or specific version?

Thank you!

**Comment by hocherie** [comment]
Thank you for bringing this to our attention. We will work on it, and let you know soon!

In the meantime, can you try this commit of OpenSfM? 
<s>https://github.com/mapillary/OpenSfM/commit/ef872b2399cf1cc036d91e950f210a7be33c2745</s>

Please try `git checkout 1106198` on the OpenSFM. We have just tried rebuilding our project with this commit, and it works. 

We will update installation instructions shortly.

Thank you!

**Comment by tonyzzzzzz** [comment]
Hello,

It seems like some of the latest updates to OpenSfm introduced this problem, could you try to roll back by `git checkout 1106198`? Our project was developing using this commit, and things were fine.

Thanks!

**Comment by hocherie** [comment]
Hi @jhkwag970 , thank you for your issue. 
I have pushed the docker image and have tested it works well with MIA. https://hub.docker.com/r/theairlab/mia
Can you please follow the instructions in this commit? https://github.com/MapItAnywhere/MapItAnywhere/commit/6dbfaa569c7f384204a9c4c5b915414c1c87451f 

Let me know if there's any problems!
